# -*- mode: ruby -*-
# vi: set ft=ruby :

# Sanbox for Google Polymer

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.synced_folder ".", "/home/vagrant/www/html", create: true
  config.ssh.forward_agent = true

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    apt-get install -y git nodejs npm
    ln -s /usr/bin/nodejs /usr/bin/node
    npm install -g bower
    npm install -g polyserve

    cp /home/vagrant/www/html/config/.bashrc /home/vagrant
  SHELL
end
